# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmaster.proto\"\x06\n\x04list\"\x16\n\x06Worker\x12\x0c\n\x04port\x18\x01 \x01(\x04\" \n\nWorkerList\x12\x12\n\nworkerList\x18\x01 \x03(\x04\x32}\n\rMasterService\x12#\n\x0fregister_worker\x12\x07.Worker\x1a\x05.list\"\x00\x12$\n\x0clist_workers\x12\x05.list\x1a\x0b.WorkerList\"\x00\x12!\n\rassign_worker\x12\x05.list\x1a\x07.Worker\"\x00\x62\x06proto3')



_LIST = DESCRIPTOR.message_types_by_name['list']
_WORKER = DESCRIPTOR.message_types_by_name['Worker']
_WORKERLIST = DESCRIPTOR.message_types_by_name['WorkerList']
list = _reflection.GeneratedProtocolMessageType('list', (_message.Message,), {
  'DESCRIPTOR' : _LIST,
  '__module__' : 'master_pb2'
  # @@protoc_insertion_point(class_scope:list)
  })
_sym_db.RegisterMessage(list)

Worker = _reflection.GeneratedProtocolMessageType('Worker', (_message.Message,), {
  'DESCRIPTOR' : _WORKER,
  '__module__' : 'master_pb2'
  # @@protoc_insertion_point(class_scope:Worker)
  })
_sym_db.RegisterMessage(Worker)

WorkerList = _reflection.GeneratedProtocolMessageType('WorkerList', (_message.Message,), {
  'DESCRIPTOR' : _WORKERLIST,
  '__module__' : 'master_pb2'
  # @@protoc_insertion_point(class_scope:WorkerList)
  })
_sym_db.RegisterMessage(WorkerList)

_MASTERSERVICE = DESCRIPTOR.services_by_name['MasterService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIST._serialized_start=16
  _LIST._serialized_end=22
  _WORKER._serialized_start=24
  _WORKER._serialized_end=46
  _WORKERLIST._serialized_start=48
  _WORKERLIST._serialized_end=80
  _MASTERSERVICE._serialized_start=82
  _MASTERSERVICE._serialized_end=207
# @@protoc_insertion_point(module_scope)
