# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import master_pb2 as master__pb2


class MasterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.register_worker = channel.unary_unary(
                '/MasterService/register_worker',
                request_serializer=master__pb2.Worker.SerializeToString,
                response_deserializer=master__pb2.list.FromString,
                )
        self.list_workers = channel.unary_unary(
                '/MasterService/list_workers',
                request_serializer=master__pb2.list.SerializeToString,
                response_deserializer=master__pb2.WorkerList.FromString,
                )
        self.assign_worker = channel.unary_unary(
                '/MasterService/assign_worker',
                request_serializer=master__pb2.list.SerializeToString,
                response_deserializer=master__pb2.Worker.FromString,
                )


class MasterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def register_worker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def list_workers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def assign_worker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'register_worker': grpc.unary_unary_rpc_method_handler(
                    servicer.register_worker,
                    request_deserializer=master__pb2.Worker.FromString,
                    response_serializer=master__pb2.list.SerializeToString,
            ),
            'list_workers': grpc.unary_unary_rpc_method_handler(
                    servicer.list_workers,
                    request_deserializer=master__pb2.list.FromString,
                    response_serializer=master__pb2.WorkerList.SerializeToString,
            ),
            'assign_worker': grpc.unary_unary_rpc_method_handler(
                    servicer.assign_worker,
                    request_deserializer=master__pb2.list.FromString,
                    response_serializer=master__pb2.Worker.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MasterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MasterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def register_worker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MasterService/register_worker',
            master__pb2.Worker.SerializeToString,
            master__pb2.list.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def list_workers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MasterService/list_workers',
            master__pb2.list.SerializeToString,
            master__pb2.WorkerList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def assign_worker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MasterService/assign_worker',
            master__pb2.list.SerializeToString,
            master__pb2.Worker.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
