# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\"\x0b\n\temptyList\"6\n\x08\x46ilepath\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\x12\x10\n\x03num\x18\x02 \x01(\x03H\x00\x88\x01\x01\x42\x06\n\x04_num\"\x18\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\t2s\n\rWorkerService\x12 \n\x08read_csv\x12\t.Filepath\x1a\x07.Result\"\x00\x12\x1f\n\x07maximum\x12\t.Filepath\x1a\x07.Result\"\x00\x12\x1f\n\x07minimum\x12\t.Filepath\x1a\x07.Result\"\x00\x62\x06proto3')



_EMPTYLIST = DESCRIPTOR.message_types_by_name['emptyList']
_FILEPATH = DESCRIPTOR.message_types_by_name['Filepath']
_RESULT = DESCRIPTOR.message_types_by_name['Result']
emptyList = _reflection.GeneratedProtocolMessageType('emptyList', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYLIST,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:emptyList)
  })
_sym_db.RegisterMessage(emptyList)

Filepath = _reflection.GeneratedProtocolMessageType('Filepath', (_message.Message,), {
  'DESCRIPTOR' : _FILEPATH,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:Filepath)
  })
_sym_db.RegisterMessage(Filepath)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'worker_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  })
_sym_db.RegisterMessage(Result)

_WORKERSERVICE = DESCRIPTOR.services_by_name['WorkerService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYLIST._serialized_start=16
  _EMPTYLIST._serialized_end=27
  _FILEPATH._serialized_start=29
  _FILEPATH._serialized_end=83
  _RESULT._serialized_start=85
  _RESULT._serialized_end=109
  _WORKERSERVICE._serialized_start=111
  _WORKERSERVICE._serialized_end=226
# @@protoc_insertion_point(module_scope)
